### ISSUE TITLE
Keep hyphen in the initials of hyphenated first names

### ISSUE THREAD

**Issue by mjthoraval** [github-young/zotero-last-author#3]
Thank you very much for the new feature to display first name as initials.
I would prefer to abbreviate `Smith, Jean-Jacques` to `Smith, J.-J.`.
See for example: https://tex.stackexchange.com/questions/344537/automatic-hyphenatation-of-first-names-in-bibtex

**Comment by github-young** [comment]
closed in [v2.1.0](https://github.com/github-young/zotero-last-author/releases/tag/v2.1.0)
